// Tests for the resolve builtin's pure parts: arguments, resolv.conf, output.

#define _POSIX_C_SOURCE 200809L

#include "internal.h"

#include <stdlib.h>
#include <string.h>

#include "../../tests/harness.h"
#include "../util/vec.h"

#define PATH_BUF 128
#define TEXT_BUF 1024
#define WORD_BUF 32
#define CMD_BUF 256

static char g_tmp[64];

// One scratch path at a time, which is all any case here needs.
static const char *fixture(const char *base, const char *content) {
    static char path[PATH_BUF];
    snprintf(path, sizeof path, "%s/%s", g_tmp, base);
    FILE *f = fopen(path, "w");
    if (f == NULL) {
        return NULL;
    }
    if (content != NULL) {
        fputs(content, f);
    }
    fclose(f);
    return path;
}

// dns.c is a stub in this clone and names no rcode, so the expected text takes
// whichever word dns_rcode_str yields; at integration that is "NOERROR".
static void rcode_word(uint8_t rcode, char *out, size_t cap) {
    const char *name = dns_rcode_str(rcode);
    if (name != NULL) {
        snprintf(out, cap, "%s", name);
    } else {
        snprintf(out, cap, "%u", (unsigned)rcode);
    }
}

// NULL when the memory stream could not be opened. Caller frees with free.
static char *render(const DnsHeader *hdr, const Vec *answers) {
    char *buf = NULL;
    size_t len = 0;
    FILE *out = open_memstream(&buf, &len);
    if (out == NULL) {
        return NULL;
    }
    resolve_print_reply(hdr, answers, out);
    fclose(out);
    return buf;
}

static DnsHeader header_of(uint16_t id, uint16_t ancount) {
    DnsHeader h;
    memset(&h, 0, sizeof h);
    h.id = id;
    h.qr = true;
    h.rd = true;
    h.ra = true;
    h.qdcount = 1;
    h.ancount = ancount;
    return h;
}

static DnsRecord record_of(const char *name, uint32_t ttl, uint16_t type) {
    DnsRecord r;
    memset(&r, 0, sizeof r);
    snprintf(r.name, sizeof r.name, "%s", name);
    r.ttl = ttl;
    r.type = type;
    r.qclass = DNS_CLASS_IN;
    return r;
}

static DnsRecord a_record(const char *name, uint32_t ttl, uint8_t a, uint8_t b,
                          uint8_t c, uint8_t d) {
    DnsRecord r = record_of(name, ttl, DNS_TYPE_A);
    r.rdlength = 4;
    r.addr[0] = a;
    r.addr[1] = b;
    r.addr[2] = c;
    r.addr[3] = d;
    return r;
}

static DnsRecord cname_record(const char *name, uint32_t ttl,
                              const char *target) {
    DnsRecord r = record_of(name, ttl, DNS_TYPE_CNAME);
    snprintf(r.target, sizeof r.target, "%s", target);
    r.rdlength = (uint16_t)(strlen(target) + 2);
    return r;
}

// resolv.conf

TEST(conf_takes_a_plain_nameserver_line) {
    const char *path = fixture("plain.conf", "nameserver 8.8.8.8\n");
    ASSERT_TRUE(path != NULL);
    char server[RESOLVE_SERVER_MAX];
    ASSERT_TRUE(resolve_conf_lookup(path, server, sizeof server));
    ASSERT_STR_EQ(server, "8.8.8.8");
}

TEST(conf_takes_the_first_of_several_nameservers) {
    const char *path =
        fixture("many.conf", "nameserver 1.1.1.1\nnameserver 9.9.9.9\n");
    ASSERT_TRUE(path != NULL);
    char server[RESOLVE_SERVER_MAX];
    ASSERT_TRUE(resolve_conf_lookup(path, server, sizeof server));
    ASSERT_STR_EQ(server, "1.1.1.1");
}

TEST(conf_skips_comments_and_blank_lines) {
    const char *path = fixture("comments.conf",
                               "# generated by something\n"
                               "\n"
                               "; another comment style\n"
                               "   \n"
                               "search example.com lan\n"
                               "options ndots:1\n"
                               "\tnameserver\t192.168.1.1\t# the router\n");
    ASSERT_TRUE(path != NULL);
    char server[RESOLVE_SERVER_MAX];
    ASSERT_TRUE(resolve_conf_lookup(path, server, sizeof server));
    ASSERT_STR_EQ(server, "192.168.1.1");
}

TEST(conf_skips_an_ipv6_nameserver_and_takes_the_next_ipv4) {
    const char *path = fixture("v6.conf",
                               "nameserver fe80::1\n"
                               "nameserver 2001:4860:4860::8888\n"
                               "nameserver 10.0.0.53\n");
    ASSERT_TRUE(path != NULL);
    char server[RESOLVE_SERVER_MAX];
    ASSERT_TRUE(resolve_conf_lookup(path, server, sizeof server));
    ASSERT_STR_EQ(server, "10.0.0.53");
}

TEST(conf_without_a_usable_line_finds_nothing) {
    char server[RESOLVE_SERVER_MAX];

    const char *empty = fixture("empty.conf", "");
    ASSERT_TRUE(empty != NULL);
    ASSERT_TRUE(!resolve_conf_lookup(empty, server, sizeof server));

    const char *only_v6 = fixture("onlyv6.conf", "nameserver ::1\n");
    ASSERT_TRUE(only_v6 != NULL);
    ASSERT_TRUE(!resolve_conf_lookup(only_v6, server, sizeof server));

    const char *no_key = fixture("nokey.conf", "search lan\noptions ndots:2\n");
    ASSERT_TRUE(no_key != NULL);
    ASSERT_TRUE(!resolve_conf_lookup(no_key, server, sizeof server));

    const char *bare = fixture("bare.conf", "nameserver\nnameserver \n");
    ASSERT_TRUE(bare != NULL);
    ASSERT_TRUE(!resolve_conf_lookup(bare, server, sizeof server));

    const char *near_miss = fixture("near.conf", "nameservers 8.8.8.8\n");
    ASSERT_TRUE(near_miss != NULL);
    ASSERT_TRUE(!resolve_conf_lookup(near_miss, server, sizeof server));

    const char *commented = fixture("hash.conf", "#nameserver 8.8.8.8\n");
    ASSERT_TRUE(commented != NULL);
    ASSERT_TRUE(!resolve_conf_lookup(commented, server, sizeof server));
}

TEST(conf_missing_file_finds_nothing) {
    char server[RESOLVE_SERVER_MAX];
    char path[PATH_BUF];
    snprintf(path, sizeof path, "%s/no_such.conf", g_tmp);
    ASSERT_TRUE(!resolve_conf_lookup(path, server, sizeof server));
}

// A line without a final newline is still a line.
TEST(conf_reads_an_unterminated_last_line) {
    const char *path = fixture("noeol.conf", "search lan\nnameserver 4.4.4.4");
    ASSERT_TRUE(path != NULL);
    char server[RESOLVE_SERVER_MAX];
    ASSERT_TRUE(resolve_conf_lookup(path, server, sizeof server));
    ASSERT_STR_EQ(server, "4.4.4.4");
}

TEST(conf_drops_an_address_too_long_for_the_buffer) {
    char text[TEXT_BUF];
    char giant[RESOLVE_SERVER_MAX * 2];
    memset(giant, '7', sizeof giant - 1);
    giant[sizeof giant - 1] = '\0';
    snprintf(text, sizeof text, "nameserver %s\nnameserver 5.5.5.5\n", giant);

    const char *path = fixture("long.conf", text);
    ASSERT_TRUE(path != NULL);
    char server[RESOLVE_SERVER_MAX];
    ASSERT_TRUE(resolve_conf_lookup(path, server, sizeof server));
    ASSERT_STR_EQ(server, "5.5.5.5");
}

// A line longer than the read buffer must not have its tail parsed as a line.
TEST(conf_does_not_split_an_overlong_line) {
    char text[4096];
    char pad[3000];
    memset(pad, 'x', sizeof pad - 1);
    pad[sizeof pad - 1] = '\0';
    snprintf(text, sizeof text, "options %s nameserver 6.6.6.6\n", pad);

    const char *path = fixture("huge.conf", text);
    ASSERT_TRUE(path != NULL);
    char server[RESOLVE_SERVER_MAX];
    ASSERT_TRUE(!resolve_conf_lookup(path, server, sizeof server));
}

TEST(conf_scan_reads_an_open_stream) {
    const char *path = fixture("stream.conf", "nameserver 172.16.0.1\n");
    ASSERT_TRUE(path != NULL);
    FILE *f = fopen(path, "r");
    ASSERT_TRUE(f != NULL);
    char server[RESOLVE_SERVER_MAX];
    bool found = resolve_conf_scan(f, server, sizeof server);
    fclose(f);
    ASSERT_TRUE(found);
    ASSERT_STR_EQ(server, "172.16.0.1");
}

// The env hook is what lets the integration script name its own fixture.
TEST(conf_honors_the_nsh_resolv_conf_override) {
    const char *path = fixture("override.conf", "nameserver 203.0.113.9\n");
    ASSERT_TRUE(path != NULL);
    setenv("NSH_RESOLV_CONF", path, 1);
    char server[RESOLVE_SERVER_MAX];
    bool found = resolve_conf_lookup(NULL, server, sizeof server);
    unsetenv("NSH_RESOLV_CONF");
    ASSERT_TRUE(found);
    ASSERT_STR_EQ(server, "203.0.113.9");
}

TEST(conf_override_pointing_nowhere_finds_nothing) {
    char path[PATH_BUF];
    snprintf(path, sizeof path, "%s/absent.conf", g_tmp);
    setenv("NSH_RESOLV_CONF", path, 1);
    char server[RESOLVE_SERVER_MAX];
    bool found = resolve_conf_lookup(NULL, server, sizeof server);
    unsetenv("NSH_RESOLV_CONF");
    ASSERT_TRUE(!found);
}

// Arguments

TEST(args_take_a_bare_name_with_the_documented_defaults) {
    char *argv[] = {"resolve", "example.com", NULL};
    ResolveOpts o;
    ASSERT_TRUE(resolve_parse_args(2, argv, &o));
    ASSERT_STR_EQ(o.name, "example.com");
    ASSERT_TRUE(o.server == NULL);
    ASSERT_EQ(o.port, 53);
    ASSERT_EQ(o.timeout_ms, 2000);
    ASSERT_EQ(o.tries, 2);
}

TEST(args_take_every_flag) {
    char *argv[] = {"resolve", "a.test", "--server", "9.9.9.9",
                    "--port",   "5353",   "--timeout", "150",
                    "--tries",  "5",      NULL};
    ResolveOpts o;
    ASSERT_TRUE(resolve_parse_args(10, argv, &o));
    ASSERT_STR_EQ(o.name, "a.test");
    ASSERT_STR_EQ(o.server, "9.9.9.9");
    ASSERT_EQ(o.port, 5353);
    ASSERT_EQ(o.timeout_ms, 150);
    ASSERT_EQ(o.tries, 5);
}

TEST(args_accept_flags_before_the_name) {
    char *argv[] = {"resolve", "--tries", "1", "late.test", NULL};
    ResolveOpts o;
    ASSERT_TRUE(resolve_parse_args(4, argv, &o));
    ASSERT_STR_EQ(o.name, "late.test");
    ASSERT_EQ(o.tries, 1);
}

TEST(args_accept_the_range_ends) {
    static const char *const flags[] = {"--port", "--timeout", "--tries"};
    static const char *const lows[] = {"1", "1", "1"};
    static const char *const highs[] = {"65535", "60000", "5"};
    for (size_t i = 0; i < sizeof flags / sizeof flags[0]; i++) {
        ResolveOpts o;
        char *low[] = {"resolve", "x.test", (char *)flags[i], (char *)lows[i],
                       NULL};
        ASSERT_TRUE(resolve_parse_args(4, low, &o));
        char *high[] = {"resolve", "x.test", (char *)flags[i],
                        (char *)highs[i], NULL};
        ASSERT_TRUE(resolve_parse_args(4, high, &o));
    }
}

TEST(args_reject_a_missing_name) {
    ResolveOpts o;
    char *none[] = {"resolve", NULL};
    ASSERT_TRUE(!resolve_parse_args(1, none, &o));

    char *only_flags[] = {"resolve", "--port", "53", NULL};
    ASSERT_TRUE(!resolve_parse_args(3, only_flags, &o));

    char *empty[] = {"resolve", "", NULL};
    ASSERT_TRUE(!resolve_parse_args(2, empty, &o));
}

TEST(args_reject_a_second_name) {
    ResolveOpts o;
    char *argv[] = {"resolve", "a.test", "b.test", NULL};
    ASSERT_TRUE(!resolve_parse_args(3, argv, &o));
}

TEST(args_reject_unknown_flags) {
    ResolveOpts o;
    char *wat[] = {"resolve", "a.test", "--wat", "1", NULL};
    ASSERT_TRUE(!resolve_parse_args(4, wat, &o));

    char *short_flag[] = {"resolve", "a.test", "-s", "1.1.1.1", NULL};
    ASSERT_TRUE(!resolve_parse_args(4, short_flag, &o));
}

TEST(args_reject_a_flag_with_no_value) {
    static const char *const flags[] = {"--server", "--port", "--timeout",
                                        "--tries"};
    for (size_t i = 0; i < sizeof flags / sizeof flags[0]; i++) {
        ResolveOpts o;
        char *argv[] = {"resolve", "a.test", (char *)flags[i], NULL};
        ASSERT_TRUE(!resolve_parse_args(3, argv, &o));
    }
}

TEST(args_reject_an_empty_server) {
    ResolveOpts o;
    char *argv[] = {"resolve", "a.test", "--server", "", NULL};
    ASSERT_TRUE(!resolve_parse_args(4, argv, &o));
}

TEST(args_reject_numbers_out_of_range) {
    static const char *const flags[] = {"--port",   "--port",  "--timeout",
                                        "--timeout", "--tries", "--tries"};
    static const char *const values[] = {"0", "65536", "0", "60001", "0", "6"};
    for (size_t i = 0; i < sizeof flags / sizeof flags[0]; i++) {
        ResolveOpts o;
        char *argv[] = {"resolve", "a.test", (char *)flags[i],
                        (char *)values[i], NULL};
        ASSERT_TRUE(!resolve_parse_args(4, argv, &o));
    }
}

TEST(args_reject_numbers_that_are_not_numbers) {
    static const char *const values[] = {"abc", "80x", "", " 80",
                                         "-1",  "0x35", "99999999999999999999"};
    for (size_t i = 0; i < sizeof values / sizeof values[0]; i++) {
        ResolveOpts o;
        char *argv[] = {"resolve", "a.test", "--port", (char *)values[i], NULL};
        ASSERT_TRUE(!resolve_parse_args(4, argv, &o));
    }
}

// Output, pinned byte for byte

TEST(output_matches_the_pinned_cname_then_a_example) {
    DnsHeader hdr = header_of(4242, 2);
    DnsRecord cname = cname_record("example.com", 300, "edge.example.net");
    DnsRecord a = a_record("edge.example.net", 60, 93, 184, 216, 34);
    Vec answers;
    vec_init(&answers);
    vec_push(&answers, &cname);
    vec_push(&answers, &a);

    char *got = render(&hdr, &answers);
    vec_free(&answers);
    ASSERT_TRUE(got != NULL);

    char rcode[WORD_BUF];
    rcode_word(0, rcode, sizeof rcode);
    char want[TEXT_BUF];
    snprintf(want, sizeof want,
             ";; id 4242 flags qr rd ra rcode %s answers 2\n"
             "example.com. 300 IN CNAME edge.example.net.\n"
             "edge.example.net. 60 IN A 93.184.216.34\n",
             rcode);

    int same = strcmp(got, want);
    if (same != 0) {
        printf("    got:  [%s]\n    want: [%s]\n", got, want);
    }
    free(got);
    ASSERT_EQ(same, 0);
}

TEST(output_keeps_a_trailing_dot_the_record_already_has) {
    DnsHeader hdr = header_of(1, 1);
    DnsRecord cname = cname_record("example.com.", 5, "edge.example.net.");
    Vec answers;
    vec_init(&answers);
    vec_push(&answers, &cname);

    char *got = render(&hdr, &answers);
    vec_free(&answers);
    ASSERT_TRUE(got != NULL);
    bool ok = strstr(got, "\nexample.com. 5 IN CNAME edge.example.net.\n") !=
              NULL;
    free(got);
    ASSERT_TRUE(ok);
}

TEST(output_prints_the_root_name_as_one_dot) {
    DnsHeader hdr = header_of(2, 1);
    DnsRecord r = a_record("", 0, 0, 0, 0, 0);
    Vec answers;
    vec_init(&answers);
    vec_push(&answers, &r);

    char *got = render(&hdr, &answers);
    vec_free(&answers);
    ASSERT_TRUE(got != NULL);
    bool ok = strstr(got, "\n. 0 IN A 0.0.0.0\n") != NULL;
    free(got);
    ASSERT_TRUE(ok);
}

TEST(output_with_zero_answers_is_the_header_line_alone) {
    DnsHeader hdr = header_of(11, 0);
    Vec answers;
    vec_init(&answers);

    char *got = render(&hdr, &answers);
    vec_free(&answers);
    ASSERT_TRUE(got != NULL);

    char rcode[WORD_BUF];
    rcode_word(0, rcode, sizeof rcode);
    char want[TEXT_BUF];
    snprintf(want, sizeof want, ";; id 11 flags qr rd ra rcode %s answers 0\n",
             rcode);
    int same = strcmp(got, want);
    free(got);
    ASSERT_EQ(same, 0);
}

TEST(output_notes_a_truncated_reply_before_the_records) {
    DnsHeader hdr = header_of(7, 1);
    hdr.tc = true;
    DnsRecord r = a_record("a.test", 10, 1, 2, 3, 4);
    Vec answers;
    vec_init(&answers);
    vec_push(&answers, &r);

    char *got = render(&hdr, &answers);
    vec_free(&answers);
    ASSERT_TRUE(got != NULL);

    char rcode[WORD_BUF];
    rcode_word(0, rcode, sizeof rcode);
    char want[TEXT_BUF];
    snprintf(want, sizeof want,
             ";; id 7 flags qr tc rd ra rcode %s answers 1\n"
             ";; truncated reply\n"
             "a.test. 10 IN A 1.2.3.4\n",
             rcode);
    int same = strcmp(got, want);
    if (same != 0) {
        printf("    got:  [%s]\n    want: [%s]\n", got, want);
    }
    free(got);
    ASSERT_EQ(same, 0);
}

TEST(output_notes_a_server_that_does_not_recurse) {
    DnsHeader hdr = header_of(8, 0);
    hdr.ra = false;
    Vec answers;
    vec_init(&answers);

    char *got = render(&hdr, &answers);
    vec_free(&answers);
    ASSERT_TRUE(got != NULL);

    char rcode[WORD_BUF];
    rcode_word(0, rcode, sizeof rcode);
    char want[TEXT_BUF];
    snprintf(want, sizeof want,
             ";; id 8 flags qr rd rcode %s answers 0\n"
             ";; recursion not available\n",
             rcode);
    int same = strcmp(got, want);
    free(got);
    ASSERT_EQ(same, 0);
}

// Both notices at once: truncation first, matching the header's flag order.
TEST(output_orders_the_truncation_notice_before_the_recursion_notice) {
    DnsHeader hdr = header_of(9, 0);
    hdr.tc = true;
    hdr.ra = false;
    Vec answers;
    vec_init(&answers);

    char *got = render(&hdr, &answers);
    vec_free(&answers);
    ASSERT_TRUE(got != NULL);

    char rcode[WORD_BUF];
    rcode_word(0, rcode, sizeof rcode);
    char want[TEXT_BUF];
    snprintf(want, sizeof want,
             ";; id 9 flags qr tc rd rcode %s answers 0\n"
             ";; truncated reply\n"
             ";; recursion not available\n",
             rcode);
    int same = strcmp(got, want);
    if (same != 0) {
        printf("    got:  [%s]\n    want: [%s]\n", got, want);
    }
    free(got);
    ASSERT_EQ(same, 0);
}

TEST(output_lists_the_set_flags_in_header_order) {
    DnsHeader all = header_of(3, 0);
    all.aa = true;
    all.tc = true;
    Vec answers;
    vec_init(&answers);

    char *got = render(&all, &answers);
    ASSERT_TRUE(got != NULL);
    bool ordered = strncmp(got, ";; id 3 flags qr aa tc rd ra rcode ",
                           strlen(";; id 3 flags qr aa tc rd ra rcode ")) == 0;
    free(got);

    DnsHeader none;
    memset(&none, 0, sizeof none);
    got = render(&none, &answers);
    vec_free(&answers);
    ASSERT_TRUE(got != NULL);

    char rcode[WORD_BUF];
    rcode_word(0, rcode, sizeof rcode);
    char want[TEXT_BUF];
    snprintf(want, sizeof want,
             ";; id 0 flags rcode %s answers 0\n"
             ";; recursion not available\n",
             rcode);
    int same = strcmp(got, want);
    free(got);

    ASSERT_TRUE(ordered);
    ASSERT_EQ(same, 0);
}

TEST(output_keeps_an_unknown_type_as_a_name_and_a_length) {
    DnsHeader hdr = header_of(12, 1);
    DnsRecord r = record_of("ipv6.test", 120, 28);
    r.rdlength = 16;
    Vec answers;
    vec_init(&answers);
    vec_push(&answers, &r);

    char *got = render(&hdr, &answers);
    vec_free(&answers);
    ASSERT_TRUE(got != NULL);
    bool ok = strstr(got, "\nipv6.test. 120 IN TYPE28 (16 bytes)\n") != NULL;
    if (!ok) {
        printf("    got: [%s]\n", got);
    }
    free(got);
    ASSERT_TRUE(ok);
}

TEST(output_names_a_class_that_is_not_in) {
    DnsHeader hdr = header_of(13, 1);
    DnsRecord r = a_record("x.test", 5, 9, 9, 9, 9);
    r.qclass = 3;
    Vec answers;
    vec_init(&answers);
    vec_push(&answers, &r);

    char *got = render(&hdr, &answers);
    vec_free(&answers);
    ASSERT_TRUE(got != NULL);
    bool ok = strstr(got, "\nx.test. 5 CLASS3 A 9.9.9.9\n") != NULL;
    free(got);
    ASSERT_TRUE(ok);
}

TEST(output_prints_an_unnamed_rcode_as_its_number) {
    DnsHeader hdr = header_of(5, 0);
    hdr.rcode = 11;
    Vec answers;
    vec_init(&answers);

    char *got = render(&hdr, &answers);
    vec_free(&answers);
    ASSERT_TRUE(got != NULL);

    char rcode[WORD_BUF];
    rcode_word(11, rcode, sizeof rcode);
    char want[TEXT_BUF];
    snprintf(want, sizeof want, ";; id 5 flags qr rd ra rcode %s answers 0\n",
             rcode);
    int same = strcmp(got, want);
    free(got);
    ASSERT_EQ(same, 0);
}

// The full 255 byte name still fits the line buffer with its dot.
TEST(output_survives_a_maximum_length_name) {
    char name[DNS_NAME_MAX + 1];
    memset(name, 'a', DNS_NAME_MAX);
    name[DNS_NAME_MAX] = '\0';

    DnsHeader hdr = header_of(14, 1);
    DnsRecord r = a_record(name, 1, 8, 8, 4, 4);
    Vec answers;
    vec_init(&answers);
    vec_push(&answers, &r);

    char *got = render(&hdr, &answers);
    vec_free(&answers);
    ASSERT_TRUE(got != NULL);
    bool ok = strstr(got, " 1 IN A 8.8.4.4\n") != NULL &&
              strlen(got) > DNS_NAME_MAX;
    free(got);
    ASSERT_TRUE(ok);
}

// Outcomes

TEST(exchange_status_is_zero_on_a_reply) {
    char msg[RESOLVE_MSG_MAX];
    ASSERT_EQ(resolve_exchange_status(NSH_OK, "1.2.3.4", 2, msg, sizeof msg),
              0);
    ASSERT_STR_EQ(msg, "");
}

TEST(exchange_status_reports_silence_with_the_try_count) {
    char msg[RESOLVE_MSG_MAX];
    ASSERT_EQ(resolve_exchange_status(NSH_ERR_NOT_FOUND, "1.2.3.4", 2, msg,
                                      sizeof msg),
              1);
    ASSERT_STR_EQ(msg, "no reply from 1.2.3.4 after 2 tries");

    ASSERT_EQ(resolve_exchange_status(NSH_ERR_NOT_FOUND, "127.0.0.1", 1, msg,
                                      sizeof msg),
              1);
    ASSERT_STR_EQ(msg, "no reply from 127.0.0.1 after 1 try");
}

TEST(exchange_status_reports_a_bad_server_and_a_socket_failure) {
    char msg[RESOLVE_MSG_MAX];
    ASSERT_EQ(
        resolve_exchange_status(NSH_ERR_INVALID, "nope", 2, msg, sizeof msg),
        1);
    ASSERT_STR_EQ(msg, "bad server address: nope");

    ASSERT_EQ(
        resolve_exchange_status(NSH_ERR_IO, "1.2.3.4", 2, msg, sizeof msg), 1);
    ASSERT_STR_EQ(msg, "socket failure talking to 1.2.3.4");
}

TEST(exchange_status_turns_an_interrupt_into_130_with_no_message) {
    char msg[RESOLVE_MSG_MAX];
    ASSERT_EQ(
        resolve_exchange_status(NSH_INTERRUPT, "1.2.3.4", 2, msg, sizeof msg),
        130);
    ASSERT_STR_EQ(msg, "");
}

TEST(exchange_status_still_explains_an_unexpected_code) {
    char msg[RESOLVE_MSG_MAX];
    ASSERT_EQ(
        resolve_exchange_status(NSH_ERR_ALLOC, "1.2.3.4", 2, msg, sizeof msg),
        1);
    ASSERT_TRUE(strncmp(msg, "lookup failed: ", 15) == 0);
}

TEST(reply_status_is_zero_for_a_matching_noerror_reply) {
    DnsHeader hdr = header_of(0x1234, 0);
    char msg[RESOLVE_MSG_MAX];
    ASSERT_EQ(resolve_reply_status(&hdr, 0x1234, msg, sizeof msg), 0);
    ASSERT_STR_EQ(msg, "");
}

TEST(reply_status_catches_a_mismatched_id_before_the_rcode) {
    DnsHeader hdr = header_of(0x1234, 0);
    hdr.rcode = 3;
    char msg[RESOLVE_MSG_MAX];
    ASSERT_EQ(resolve_reply_status(&hdr, 0x4321, msg, sizeof msg), 1);
    ASSERT_STR_EQ(msg, "reply id mismatch");
}

TEST(reply_status_reports_a_non_zero_rcode) {
    DnsHeader hdr = header_of(7, 0);
    hdr.rcode = 3;
    char msg[RESOLVE_MSG_MAX];
    ASSERT_EQ(resolve_reply_status(&hdr, 7, msg, sizeof msg), 1);

    char rcode[WORD_BUF];
    rcode_word(3, rcode, sizeof rcode);
    char want[TEXT_BUF];
    if (dns_rcode_str(3) != NULL) {
        snprintf(want, sizeof want, "server returned %s", rcode);
    } else {
        snprintf(want, sizeof want, "server returned rcode %s", rcode);
    }
    ASSERT_STR_EQ(msg, want);
}

TEST(reply_status_reports_every_non_zero_rcode) {
    for (unsigned code = 1; code <= 15; code++) {
        DnsHeader hdr = header_of(1, 0);
        hdr.rcode = (uint8_t)code;
        char msg[RESOLVE_MSG_MAX];
        ASSERT_EQ(resolve_reply_status(&hdr, 1, msg, sizeof msg), 1);
        ASSERT_TRUE(strncmp(msg, "server returned ", 16) == 0);
    }
}

static void setup(void) {
    snprintf(g_tmp, sizeof g_tmp, "/tmp/nsh_resolve_XXXXXX");
    if (mkdtemp(g_tmp) == NULL) {
        fprintf(stderr, "resolve_test: mkdtemp failed\n");
        exit(1);
    }
}

static void teardown(void) {
    char cmd[CMD_BUF];
    snprintf(cmd, sizeof cmd, "rm -rf %s", g_tmp);
    if (system(cmd) != 0) {
        fprintf(stderr, "resolve_test: could not remove %s\n", g_tmp);
    }
}

// Every conf case writes a fixture into the scratch directory, so main is here.
int main(void) {
    setup();
    int failures = 0;
    for (int i = 0; i < nsh_test_count; i++) {
        int failed = 0;
        nsh_test_cases[i].fn(&failed);
        printf("  %s %s\n", failed ? "FAIL" : "ok  ", nsh_test_cases[i].name);
        failures += failed;
    }
    printf("  %d test(s), %d failed\n", nsh_test_count, failures);
    teardown();
    return failures == 0 ? 0 : 1;
}
